name: C/C++ Nightly macos

on:
  push:
    branches:
      - Nigthly
      - nightly_dev
      - nightly_master
      - debug_macos

jobs:
  build:

    runs-on: macos-12


    steps:
    - uses: actions/checkout@v3
    - name: check autoconf version
      run: |
        autoconf --version
        automake --version
        glibtool --version
        which autoreconf
        ls /usr/local/bin
    - name: build deps & slicer
      run: ./BuildMacOS.sh -dsi
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: nightly_macos.app
        path: build/pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app
    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: nightly_macos.dmg
        path: ${{ github.event.repository.name }}.dmg
